#!/usr/bin/env python3
"""Workit — Personal Work Hub"""

from flask import Flask, request, jsonify, render_template
from pathlib import Path
from collections import defaultdict
from datetime import datetime
import yaml, json, os, sys, shutil, uuid

BASE_DIR         = Path(__file__).parent
DATA_DIR         = BASE_DIR / "data"
SSH_YAML         = DATA_DIR / "ssh" / "conn_info.yaml"
ACCTS_FILE       = Path.home() / ".workit" / "accounts" / "accounts.json"
SSH_CONFIG       = Path.home() / ".ssh" / "config"
KEYS_ROOT        = Path.home() / ".ssh" / "keys"
ENV_ORDER        = ["dev", "test", "stg", "prd"]
KUBE_JSON        = DATA_DIR / "kube" / "contexts.json"
KUBE_CONFIG      = Path.home() / ".kube" / "config"
KUBE_CONFIGS_DIR = Path.home() / ".kube" / "configs"

app = Flask(__name__)

_DEFAULT_SSH_YAML = """\
version: "1.0"

defaults:
  user: ec2-user
  port: 22
  keys_dir: ~/.ssh/keys
  key_extension: .pem
  forward_agent: false
  server_alive_interval: 60
  server_alive_count_max: 3

servers:
"""


def _init():
    (DATA_DIR / "ssh").mkdir(parents=True, exist_ok=True)
    if not SSH_YAML.exists():
        SSH_YAML.write_text(_DEFAULT_SSH_YAML)
    # Accounts: stored outside repo at ~/.workit/accounts/
    ACCTS_FILE.parent.mkdir(parents=True, exist_ok=True)
    old_accts = DATA_DIR / "accounts.json"
    if old_accts.exists() and not ACCTS_FILE.exists():
        import shutil as _shutil
        _shutil.copy2(str(old_accts), str(ACCTS_FILE))
        old_accts.unlink()
    elif not ACCTS_FILE.exists():
        ACCTS_FILE.write_text('{"accounts": []}')
    ACCTS_FILE.chmod(0o600)
    (DATA_DIR / "kube").mkdir(parents=True, exist_ok=True)
    if not KUBE_JSON.exists():
        KUBE_JSON.write_text('{"contexts": []}')
    KUBE_CONFIGS_DIR.mkdir(parents=True, exist_ok=True)


# ═══ SSH helpers ══════════════════════════════════════════════

def _load_ssh():
    with open(SSH_YAML) as f:
        return yaml.safe_load(f) or {}


def _yv(v):
    return ("true" if v else "false") if isinstance(v, bool) else str(v)


def _save_ssh(data):
    d, servers = data.get("defaults", {}), data.get("servers", [])
    by_env = {}
    for s in servers:
        by_env.setdefault(s["env"], []).append(s)

    out = ['version: "1.0"', "", "defaults:"]
    for k, v in d.items():
        out.append(f"  {k}: {_yv(v)}")
    out += ["", "servers:"]
    for env in ENV_ORDER:
        if env not in by_env:
            continue
        out.append(f"\n  # ── {env} {'─' * 50}")
        for s in by_env[env]:
            items = list(s.items())
            k0, v0 = items[0]
            out.append(f"  - {k0}: {_yv(v0)}")
            for k, v in items[1:]:
                out.append(f"    {k}: {_yv(v)}")
            out.append("")
    with open(SSH_YAML, "w") as f:
        f.write("\n".join(out) + "\n")


def _alias(project, env, role):
    return f"{project}-{env}-{role}"


def _key_path(project, env, role, ext=".pem"):
    return KEYS_ROOT / env / f"{_alias(project, env, role)}{ext}"


def _enrich(s, d):
    p, e, r = s["project"], s["env"], s["role"]
    kp = _key_path(p, e, r, d.get("key_extension", ".pem"))
    return {
        **s,
        "alias":         _alias(p, e, r),
        "user":          s.get("user",          d.get("user",          "ec2-user")),
        "port":          s.get("port",          d.get("port",          22)),
        "proxy_jump":    s.get("proxy_jump",    ""),
        "forward_agent": s.get("forward_agent", d.get("forward_agent", False)),
        "key_path":      str(kp),
        "key_exists":    kp.exists(),
        "description":   s.get("description", ""),
    }


def _save_key(kp, file=None, text=None, local_path=None):
    kp.parent.mkdir(parents=True, exist_ok=True)
    kp.parent.chmod(0o700)
    if file:
        file.save(str(kp))
    elif text:
        content = text.strip()
        if not content.endswith("\n"):
            content += "\n"
        kp.write_text(content)
    elif local_path:
        lp = Path(os.path.expanduser(local_path))
        if not lp.exists():
            raise FileNotFoundError(f"파일을 찾을 수 없습니다: {lp}")
        if lp.resolve() != kp.resolve():
            shutil.copy2(str(lp), str(kp))
    os.chmod(str(kp), 0o600)


def _build_ssh_config(data):
    d, servers = data.get("defaults", {}), data.get("servers", [])
    by_env = defaultdict(list)
    for s in servers:
        by_env[s["env"]].append(s)

    def rv(s, field, fallback=None):
        return s.get(field, d.get(field, fallback))

    lines = [
        f"# Generated by Workit  [{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}]",
        f"# Source: {SSH_YAML}", "",
    ]
    for env in ENV_ORDER:
        if env not in by_env:
            continue
        lines += [f"# {'=' * 54}", f"# Environment: {env.upper()}", f"# {'=' * 54}", ""]
        for s in by_env[env]:
            p, r = s["project"], s["role"]
            a  = _alias(p, env, r)
            kp = KEYS_ROOT / env / f"{a}{rv(s, 'key_extension', '.pem')}"
            fa = "yes" if rv(s, "forward_agent", False) else "no"
            lines += [
                f"# [{env}] {p} / {r}", f"Host {a}",
                f"    HostName          {s['hostname']}",
                f"    User              {rv(s, 'user', 'ec2-user')}",
                f"    Port              {rv(s, 'port', 22)}",
                f"    IdentityFile      {kp}",
                f"    IdentitiesOnly    yes",
                f"    ForwardAgent      {fa}",
                f"    ServerAliveInterval   {rv(s, 'server_alive_interval', 60)}",
                f"    ServerAliveCountMax   {rv(s, 'server_alive_count_max', 3)}",
            ]
            if s.get("proxy_jump"):
                lines.append(f"    ProxyJump         {s['proxy_jump']}")
            lines.append("")
    return "\n".join(lines)


# ═══ Accounts helpers ═════════════════════════════════════════

def _load_accounts():
    with open(ACCTS_FILE) as f:
        return json.load(f)


def _save_accounts(data):
    with open(ACCTS_FILE, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


# ═══ Kubernetes helpers ═══════════════════════════════════════

def _load_kube():
    with open(KUBE_JSON) as f:
        return json.load(f)


def _save_kube(data):
    with open(KUBE_JSON, "w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def _kube_filename(entry):
    def s(t):
        return "".join(c if c.isalnum() or c == "-" else "-" for c in str(t).lower()).strip("-") or "ctx"
    ctx = s(entry.get("context_name") or "ctx")
    return f"{ctx}.yaml"


def _write_kube_context_file(entry):
    ctx_name = entry.get("context_name", "")
    # Use ctx_name for cluster/user names inside the file so each file has unique
    # names and won't collide when multiple configs are merged via KUBECONFIG.
    file_cl  = ctx_name or entry.get("cluster_name", "")
    file_usr = ctx_name or entry.get("user_name", "")
    cl_data  = dict(entry.get("_cluster") or {})
    if entry.get("server"):
        cl_data["server"] = entry["server"]
    raw   = dict(entry.get("_raw_ctx") or {})
    ctx_d = {k: v for k, v in raw.items() if k not in ("cluster", "user", "namespace")}
    ctx_d["cluster"] = file_cl
    ctx_d["user"]    = file_usr
    if entry.get("namespace"):
        ctx_d["namespace"] = entry["namespace"]
    elif "namespace" in raw:
        ctx_d["namespace"] = raw["namespace"]
    cfg = {
        "apiVersion":      "v1",
        "kind":            "Config",
        "preferences":     {},
        "clusters":        [{"name": file_cl, "cluster": cl_data}] if file_cl else [],
        "contexts":        [{"name": ctx_name, "context": ctx_d}],
        "current-context": ctx_name,
        "users":           [{"name": file_usr, "user": entry.get("_user") or {}}] if file_usr else [],
    }
    KUBE_CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
    fpath = KUBE_CONFIGS_DIR / _kube_filename(entry)
    fpath.write_text(yaml.dump(cfg, default_flow_style=False, allow_unicode=True))
    fpath.chmod(0o600)
    return str(fpath)


def _remove_from_kube_config(ctx_name: str):
    """Remove a context (and orphaned cluster/user) from ~/.kube/config."""
    if not KUBE_CONFIG.exists() or not ctx_name:
        return
    try:
        cfg = yaml.safe_load(KUBE_CONFIG.read_text()) or {}
        contexts = cfg.get("contexts") or []
        ctx = next((c for c in contexts if (c or {}).get("name") == ctx_name), None)
        if not ctx:
            return
        cl_ref  = ((ctx.get("context") or {})).get("cluster", "")
        usr_ref = ((ctx.get("context") or {})).get("user", "")
        cfg["contexts"] = [c for c in contexts if (c or {}).get("name") != ctx_name]
        remaining_cl  = {(c.get("context") or {}).get("cluster") for c in cfg["contexts"] if c}
        remaining_usr = {(c.get("context") or {}).get("user")    for c in cfg["contexts"] if c}
        if cl_ref and cl_ref not in remaining_cl:
            cfg["clusters"] = [c for c in (cfg.get("clusters") or []) if (c or {}).get("name") != cl_ref]
        if usr_ref and usr_ref not in remaining_usr:
            cfg["users"] = [u for u in (cfg.get("users") or []) if (u or {}).get("name") != usr_ref]
        if cfg.get("current-context") == ctx_name:
            rem = cfg.get("contexts") or []
            cfg["current-context"] = rem[0]["name"] if rem else ""
        KUBE_CONFIG.write_text(yaml.dump(cfg, default_flow_style=False, allow_unicode=True))
    except Exception:
        pass


# ═══ Routes ═══════════════════════════════════════════════════

@app.route("/")
def index():
    from flask import make_response
    resp = make_response(render_template("index.html"))
    resp.headers["Cache-Control"] = "no-store"
    return resp


# ── SSH ───────────────────────────────────────────────────────

@app.route("/api/ssh/servers")
def ssh_list():
    data = _load_ssh()
    d    = data.get("defaults", {})
    servers = [_enrich(s, d) for s in data.get("servers", [])]
    return jsonify({"servers": servers, "aliases": [s["alias"] for s in servers]})


@app.route("/api/ssh/servers", methods=["POST"])
def ssh_add():
    project     = request.form.get("project",       "").strip()
    env         = request.form.get("env",           "").strip()
    role        = request.form.get("role",          "").strip()
    hostname    = request.form.get("hostname",      "").strip()
    user        = request.form.get("user",          "").strip()
    port_s      = request.form.get("port",          "22").strip()
    proxy_jump  = request.form.get("proxy_jump",    "").strip()
    fwd         = request.form.get("forward_agent", "") == "true"
    description = request.form.get("description",   "").strip()
    key_file    = request.files.get("key_file")
    key_text    = request.form.get("key_text",      "").strip()

    if not all([project, env, role, hostname]):
        return jsonify({"error": "project, env, role, hostname are required"}), 400
    if env not in ENV_ORDER:
        return jsonify({"error": f"env must be one of {ENV_ORDER}"}), 400

    data    = _load_ssh()
    d       = data.get("defaults", {})
    servers = data.get("servers", [])

    a = _alias(project, env, role)
    if any(_alias(s["project"], s["env"], s["role"]) == a for s in servers):
        return jsonify({"error": f"'{a}' already exists"}), 400

    new = {"project": project, "env": env, "role": role, "hostname": hostname}
    if user and user != d.get("user"):
        new["user"] = user
    try:
        p = int(port_s)
        if p != int(d.get("port", 22)):
            new["port"] = p
    except (ValueError, TypeError):
        pass
    if proxy_jump:
        new["proxy_jump"] = proxy_jump
    if fwd:
        new["forward_agent"] = True
    if description:
        new["description"] = description

    has_file = key_file and key_file.filename
    if has_file or key_text:
        kp = _key_path(project, env, role, d.get("key_extension", ".pem"))
        _save_key(kp, file=key_file if has_file else None, text=key_text or None)

    servers.append(new)
    data["servers"] = servers
    _save_ssh(data)
    return jsonify(_enrich(new, d)), 201


@app.route("/api/ssh/servers/<path:a>", methods=["PUT"])
def ssh_update(a):
    project     = request.form.get("project",       "").strip()
    env         = request.form.get("env",           "").strip()
    role        = request.form.get("role",          "").strip()
    hostname    = request.form.get("hostname",      "").strip()
    user        = request.form.get("user",          "").strip()
    port_s      = request.form.get("port",          "22").strip()
    proxy_jump  = request.form.get("proxy_jump",    "").strip()
    fwd         = request.form.get("forward_agent", "") == "true"
    description = request.form.get("description",   "").strip()
    key_file    = request.files.get("key_file")
    key_text    = request.form.get("key_text",      "").strip()

    if not all([project, env, role, hostname]):
        return jsonify({"error": "project, env, role, hostname are required"}), 400
    if env not in ENV_ORDER:
        return jsonify({"error": f"env must be one of {ENV_ORDER}"}), 400

    data    = _load_ssh()
    d       = data.get("defaults", {})
    servers = data.get("servers", [])

    target_idx = next((i for i, s in enumerate(servers)
                       if _alias(s["project"], s["env"], s["role"]) == a), None)
    if target_idx is None:
        return jsonify({"error": "not found"}), 404

    old_server = servers[target_idx]
    new_alias  = _alias(project, env, role)
    if new_alias != a:
        if any(_alias(s["project"], s["env"], s["role"]) == new_alias
               for i, s in enumerate(servers) if i != target_idx):
            return jsonify({"error": f"'{new_alias}' already exists"}), 400

    updated = {"project": project, "env": env, "role": role, "hostname": hostname}
    if user and user != d.get("user"):
        updated["user"] = user
    try:
        p = int(port_s)
        if p != int(d.get("port", 22)):
            updated["port"] = p
    except (ValueError, TypeError):
        pass
    if proxy_jump:
        updated["proxy_jump"] = proxy_jump
    if fwd:
        updated["forward_agent"] = True
    if description:
        updated["description"] = description

    old_kp = _key_path(old_server["project"], old_server["env"], old_server["role"],
                       d.get("key_extension", ".pem"))
    new_kp = _key_path(project, env, role, d.get("key_extension", ".pem"))
    has_new_key = (key_file and key_file.filename) or key_text
    if has_new_key:
        _save_key(new_kp, file=key_file if (key_file and key_file.filename) else None,
                  text=key_text or None)
    elif old_kp != new_kp and old_kp.exists():
        new_kp.parent.mkdir(parents=True, exist_ok=True)
        new_kp.parent.chmod(0o700)
        shutil.copy2(str(old_kp), str(new_kp))
        os.chmod(str(new_kp), 0o600)

    servers[target_idx] = updated
    data["servers"]     = servers
    _save_ssh(data)
    return jsonify(_enrich(updated, d))


@app.route("/api/ssh/servers/<path:a>", methods=["DELETE"])
def ssh_delete(a):
    data     = _load_ssh()
    original = data.get("servers", [])
    data["servers"] = [s for s in original if _alias(s["project"], s["env"], s["role"]) != a]
    if len(data["servers"]) == len(original):
        return jsonify({"error": "not found"}), 404
    _save_ssh(data)
    return jsonify({"ok": True})


@app.route("/api/ssh/servers/<path:a>/key", methods=["POST"])
def ssh_upload_key(a):
    file       = request.files.get("file")
    text       = request.form.get("text",       "").strip()
    local_path = request.form.get("local_path", "").strip()

    if not file and not text and not local_path:
        return jsonify({"error": "file, text, local_path 중 하나는 필요합니다"}), 400

    data   = _load_ssh()
    d      = data.get("defaults", {})
    target = next((s for s in data.get("servers", []) if _alias(s["project"], s["env"], s["role"]) == a), None)
    if not target:
        parts = a.split("-", 2)
        if len(parts) != 3:
            return jsonify({"error": f"'{a}' not found"}), 404
        target = {"project": parts[0], "env": parts[1], "role": parts[2]}

    kp = _key_path(target["project"], target["env"], target["role"], d.get("key_extension", ".pem"))
    try:
        _save_key(kp, file=file if (file and file.filename) else None,
                  text=text or None, local_path=local_path or None)
    except FileNotFoundError as e:
        return jsonify({"error": str(e)}), 400
    return jsonify({"ok": True, "path": str(kp)})


@app.route("/api/ssh/keys/scan")
def ssh_scan_keys():
    home  = Path.home()
    env_q = request.args.get("env", "").strip()
    dirs  = [home / ".ssh", home / "Downloads", home / "Desktop", home / "Documents"]
    for env in ([env_q] if env_q in ENV_ORDER else ENV_ORDER):
        d = KEYS_ROOT / env
        if d.exists():
            dirs.append(d)
    found, seen = [], set()
    for d in dirs:
        if not d.exists():
            continue
        for f in sorted(f for ext in ("*.pem", "*.key") for f in d.glob(ext) if f.is_file()):
            if str(f) in seen:
                continue
            seen.add(str(f))
            found.append({"path": str(f), "name": f.name, "dir": str(f.parent).replace(str(home), "~"), "size_kb": round(f.stat().st_size / 1024, 1)})
    return jsonify({"files": found})


@app.route("/api/ssh/apply", methods=["POST"])
def ssh_apply():
    data    = _load_ssh()
    content = _build_ssh_config(data)
    if SSH_CONFIG.exists() and SSH_CONFIG.read_text().strip():
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        shutil.copy2(SSH_CONFIG, SSH_CONFIG.with_name(f"config.backup.{ts}"))
    d = data.get("defaults", {})
    keys_root = Path(os.path.expanduser(d.get("keys_dir", "~/.ssh/keys")))
    for env in {s["env"] for s in data.get("servers", [])}:
        env_dir = keys_root / env
        env_dir.mkdir(parents=True, exist_ok=True)
        env_dir.chmod(0o700)
    SSH_CONFIG.write_text(content)
    SSH_CONFIG.chmod(0o600)
    return jsonify({"ok": True, "output": "~/.ssh/config 업데이트 완료"})


# ── Kubernetes ────────────────────────────────────────────────

def _parse_kubeconfig(text):
    """Parse a kubeconfig YAML and return (clusters, users, contexts) dicts."""
    try:
        cfg = yaml.safe_load(text) or {}
    except Exception:
        return None, None, None
    if not isinstance(cfg, dict) or cfg.get("kind") != "Config":
        return None, None, None
    clusters = {c["name"]: c.get("cluster") or {} for c in (cfg.get("clusters") or []) if "name" in c}
    users    = {u["name"]: u.get("user")    or {} for u in (cfg.get("users")    or []) if "name" in u}
    contexts = cfg.get("contexts") or []
    return clusters, users, contexts


def _import_contexts(data, clusters, users, ctx_list, known):
    """Import contexts into data dict if not already known. Returns changed flag."""
    changed = False
    for ctx in ctx_list:
        ctx_name = ctx.get("name", "")
        if not ctx_name or ctx_name in known:
            continue
        ctx_data  = ctx.get("context") or {}
        cl_name   = ctx_data.get("cluster",   "")
        user_name = ctx_data.get("user",      "")
        namespace = ctx_data.get("namespace", "")
        cl_info   = dict(clusters.get(cl_name, {}))
        data.setdefault("contexts", []).append({
            "id":           str(uuid.uuid4()),
            "context_name": ctx_name,
            "cluster_name": cl_name,
            "user_name":    user_name,
            "namespace":    namespace,
            "server":       cl_info.get("server", ""),
            "_cluster":     cl_info,
            "_user":        dict(users.get(user_name, {})),
            "_raw_ctx":     dict(ctx_data),
            "project":      "",
            "env":          "",
            "description":  "",
        })
        known.add(ctx_name)
        changed = True
    return changed


@app.route("/api/kube/contexts")
def kube_list():
    data    = _load_kube()
    known   = {c["context_name"] for c in data.get("contexts", [])}
    changed = False

    # Always re-sync from ~/.kube/config — system-managed contexts always visible
    if KUBE_CONFIG.exists():
        clusters, users, ctx_list = _parse_kubeconfig(KUBE_CONFIG.read_text())
        if ctx_list is not None:
            changed |= _import_contexts(data, clusters, users, ctx_list, known)

    # Also import from ~/.kube/configs/*.yaml (workit-managed files)
    if KUBE_CONFIGS_DIR.exists():
        for fpath in sorted(KUBE_CONFIGS_DIR.glob("*.yaml")):
            clusters, users, ctx_list = _parse_kubeconfig(fpath.read_text())
            if ctx_list is not None:
                changed |= _import_contexts(data, clusters, users, ctx_list, known)

    if changed:
        _save_kube(data)

    return jsonify({"contexts": data.get("contexts", [])})


@app.route("/api/kube/parse", methods=["POST"])
def kube_parse():
    text = request.form.get("text", "").strip()
    f    = request.files.get("file")
    if f and f.filename:
        try:
            text = f.read().decode("utf-8")
        except Exception:
            return jsonify({"error": "파일 읽기 실패"}), 400
    if not text:
        return jsonify({"error": "내용이 없습니다"}), 400
    try:
        cfg = yaml.safe_load(text)
    except yaml.YAMLError as e:
        return jsonify({"error": f"YAML 파싱 오류: {str(e)[:200]}"}), 400
    if not isinstance(cfg, dict) or cfg.get("kind") != "Config":
        return jsonify({"error": "kubeconfig 형식이 아닙니다 (kind: Config 필요)"}), 400

    clusters = {c["name"]: c.get("cluster") or {} for c in (cfg.get("clusters") or []) if "name" in c}
    users    = {u["name"]: u.get("user")    or {} for u in (cfg.get("users")    or []) if "name" in u}
    result   = []
    for ctx in (cfg.get("contexts") or []):
        ctx_name  = ctx.get("name", "")
        ctx_data  = ctx.get("context") or {}
        cl_name   = ctx_data.get("cluster",   "")
        user_name = ctx_data.get("user",      "")
        namespace = ctx_data.get("namespace", "")
        cl_info   = dict(clusters.get(cl_name, {}))
        result.append({
            "context_name": ctx_name,
            "cluster_name": cl_name,
            "user_name":    user_name,
            "namespace":    namespace,
            "server":       cl_info.get("server", ""),
            "_cluster":     cl_info,
            "_user":        dict(users.get(user_name, {})),
            "_raw_ctx":     dict(ctx_data),
            "project":      "",
            "env":          "",
            "description":  "",
        })

    if not result:
        return jsonify({"error": "contexts를 찾을 수 없습니다"}), 400
    return jsonify({"contexts": result})


@app.route("/api/kube/contexts", methods=["POST"])
def kube_add():
    body     = request.get_json() or {}
    ctx_name = (body.get("context_name") or "").strip()
    if not ctx_name:
        return jsonify({"error": "context_name이 필요합니다"}), 400

    data = _load_kube()
    if any(c["context_name"] == ctx_name for c in data.get("contexts", [])):
        return jsonify({"error": f"'{ctx_name}' 이미 존재합니다"}), 400

    server  = (body.get("server") or "").strip()
    cl_info = dict(body.get("_cluster") or {})
    if server:
        cl_info["server"] = server

    env = (body.get("env") or "").strip()
    if env and env not in ENV_ORDER:
        env = ""

    entry = {
        "id":           str(uuid.uuid4()),
        "context_name": ctx_name,
        "cluster_name": (body.get("cluster_name") or "").strip(),
        "user_name":    (body.get("user_name")    or "").strip(),
        "namespace":    (body.get("namespace")    or "").strip(),
        "server":       server,
        "_cluster":     cl_info,
        "_user":        dict(body.get("_user") or {}),
        "_raw_ctx":     dict(body.get("_raw_ctx") or {}),
        "project":      (body.get("project") or "").strip(),
        "env":          env,
        "description":  (body.get("description") or "").strip(),
    }
    data.setdefault("contexts", []).append(entry)
    _save_kube(data)

    try:
        _write_kube_context_file(entry)
    except Exception:
        pass

    return jsonify(entry), 201


@app.route("/api/kube/contexts/<cid>", methods=["PUT"])
def kube_update(cid):
    body = request.get_json() or {}
    data = _load_kube()
    target = next((c for c in data.get("contexts", []) if c["id"] == cid), None)
    if not target:
        return jsonify({"error": "not found"}), 404

    old_filename = _kube_filename(target)

    env = (body.get("env") or "").strip()
    if env and env not in ENV_ORDER:
        env = ""

    for field in ("context_name", "cluster_name", "user_name", "namespace",
                  "server", "project", "description"):
        if field in body:
            target[field] = (body[field] or "").strip()
    target["env"] = env

    if body.get("_cluster") is not None:
        cl = dict(body["_cluster"])
        if target.get("server"):
            cl["server"] = target["server"]
        target["_cluster"] = cl
    if body.get("_user") is not None:
        target["_user"] = dict(body["_user"])
    if body.get("_raw_ctx") is not None:
        target["_raw_ctx"] = dict(body["_raw_ctx"])

    _save_kube(data)

    old_fpath = KUBE_CONFIGS_DIR / old_filename
    new_fpath = KUBE_CONFIGS_DIR / _kube_filename(target)
    if old_fpath.exists() and old_fpath.resolve() != new_fpath.resolve():
        old_fpath.unlink()
    try:
        _write_kube_context_file(target)
    except Exception:
        pass

    return jsonify(target)


@app.route("/api/kube/contexts/<cid>", methods=["DELETE"])
def kube_delete(cid):
    data = _load_kube()
    orig = data.get("contexts", [])
    target = next((c for c in orig if c["id"] == cid), None)
    if not target:
        return jsonify({"error": "not found"}), 404
    data["contexts"] = [c for c in orig if c["id"] != cid]
    _save_kube(data)

    fpath = KUBE_CONFIGS_DIR / _kube_filename(target)
    if fpath.exists():
        fpath.unlink()

    _remove_from_kube_config(target.get("context_name", ""))

    return jsonify({"ok": True})


@app.route("/api/kube/apply", methods=["POST"])
def kube_apply():
    workit_ctxs = _load_kube().get("contexts", [])
    KUBE_CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for c in workit_ctxs:
        try:
            _write_kube_context_file(c)
            written += 1
        except Exception:
            pass
    return jsonify({"ok": True, "output": f"~/.kube/configs/ 저장 완료 ({written}개 파일)"})


# ── Accounts ──────────────────────────────────────────────────

@app.route("/api/accounts")
def accts_list():
    return jsonify(_load_accounts())


@app.route("/api/accounts", methods=["POST"])
def accts_add():
    body = request.get_json() or {}
    data = _load_accounts()
    new  = {
        "id":       str(uuid.uuid4()),
        "name":     body.get("name",     "").strip(),
        "category": body.get("category", "기타").strip(),
        "username": body.get("username", "").strip(),
        "password": body.get("password", "").strip(),
        "url":      body.get("url",      "").strip(),
        "notes":    body.get("notes",    "").strip(),
    }
    if not new["name"]:
        return jsonify({"error": "name is required"}), 400
    data["accounts"].append(new)
    _save_accounts(data)
    return jsonify(new), 201


@app.route("/api/accounts/<aid>", methods=["PUT"])
def accts_update(aid):
    body = request.get_json() or {}
    data = _load_accounts()
    for a in data["accounts"]:
        if a["id"] == aid:
            for f in ("name", "category", "username", "password", "url", "notes"):
                if f in body:
                    a[f] = body[f]
            _save_accounts(data)
            return jsonify(a)
    return jsonify({"error": "not found"}), 404


@app.route("/api/accounts/<aid>", methods=["DELETE"])
def accts_delete(aid):
    data = _load_accounts()
    orig = data["accounts"]
    data["accounts"] = [a for a in orig if a["id"] != aid]
    if len(data["accounts"]) == len(orig):
        return jsonify({"error": "not found"}), 404
    _save_accounts(data)
    return jsonify({"ok": True})


# ═══ Entry ════════════════════════════════════════════════════

if __name__ == "__main__":
    _init()
    port  = int(os.environ.get("WORKIT_PORT", 5010))
    debug = "--debug" in sys.argv
    if not debug:
        print(f"  Workit  →  http://localhost:{port}")
    app.run(debug=debug, port=port, host="0.0.0.0")
